# Generated by Django 2.2.10 on 2020-09-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsdetail',
            old_name='GoodsDetailName',
            new_name='goodsDetailName',
        ),
        migrations.AlterField(
            model_name='color',
            name='colorurl',
            field=models.ImageField(upload_to='color/'),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='gdurl',
            field=models.ImageField(upload_to=''),
        ),
    ]
