# Generated by Django 2.2.10 on 2020-09-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payway',
            field=models.CharField(default='alipay', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='待支付', max_length=20),
        ),
    ]
