# Generated by Django 2.2.10 on 2020-09-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200923_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_id',
            new_name='address',
        ),
    ]
